name: qna

services:
  core-service:
    platform: linux/amd64
    container_name: core
    env_file:
      - core.env
    build:
      dockerfile: Dockerfile

    # Command to run 'core' container:
    command: uvicorn core.main.app:APP --host 0.0.0.0 --port 7070

    # port forwarding
    ports:
      - "7070:7070"

    # CORE service â€” secondary functionality to DB service
    depends_on:
      postgres-service:
        condition: service_healthy

    restart: unless-stopped

  postgres-service:
    platform: linux/amd64
    image: postgres:latest
    container_name: postgres

    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5430:5432" # map network port 5430 to container port 5432

    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata # map local volume `pgdata` (left) to a container path for `pgdata`

    command: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5

    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  pgdata:
    driver: local